// Generated by CoffeeScript 1.3.3
(function() {

  $.ajax({
    url: "http://addyosmani.github.com/todomvc/architecture-examples/backbone/",
    success: function(data, dataType) {
      return console.log(data);
    }
  });

}).call(this);
